const ESCAPE_KEY_CODE = 27
const ENTER_KEY_CODE = 13

const REACT_APP_CLOUD_NAME = 'do7mce7ni'
const REACT_APP_UPLOAD_PRESET = 'uo9ubii7'

export {
    ESCAPE_KEY_CODE,
    ENTER_KEY_CODE,
    REACT_APP_CLOUD_NAME,
    REACT_APP_UPLOAD_PRESET
}